style: 0
rate: 50
delay: 1.0
rosbag: false
topics:
 - topic: /net/image/theora
 - topic: /scan/shaped
 - topic: /mavros/local_position/pose
 - topic: /mavros/setpoint_velocity/cmd_vel
 - topic: /mavtest/local_plan
 - topic: /rtabmap/odom
 - topic: /mavros/state
 - topic: /mavros/battery
