delay: 2500
queue: 50
device: wlan10
nodes:
 - id: 2
   mac: 00:c0:ca:83:3e:c0
 - id: 1
   mac: 00:c0:ca:95:4a:eb
 - id: 0
   mac: 00:c0:ca:95:4a:ea
routes:
 - dest: 0
   next: 2
use_ip: false
feedback: false
quiet: false
# 1 cuad -> dron
# 2 cuad -> BS
# 3 cuad -> RPi
